repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        files: ^backend/.*\.py$
        additional_dependencies: []
        args: ["--config=backend/pyproject.toml"]

  - repo: https://github.com/pycqa/isort
    rev: 6.0.0
    hooks:
      - id: isort
        files: ^backend/.*\.py$
        args: ["--settings-path=backend/pyproject.toml"]
